= Solution Pattern: App Connectivity with Policy-as-Code
:sectnums:
:sectlinks:
:doctype: book

= Architecture 

Introduction for the architecture of this solution pattern.

== Common Challenges addressed

* To provide an connectivity solution that leverages Gateway API as it's foundation that enable platform engineers and application developers to collaborate to connect, secure, protect and observe their HTTP based APIs and infrastructure leveraging CRD based APIs rather than additional heavy weight platforms. 

* To provide a lightweight layer of API mgmt focused tooling that provides an “API mgmt lens” that compliments the core connectivity features.


[#tech_stack]
== Technology Stack

// Change links and text here as you see fit.
* Red Hat supported products
** https://developers.redhat.com/products/red-hat-connectivity-link/overview[Red Hat Connectivity Link^]
** https://www.redhat.com/en/technologies/cloud-computing/openshift[Red Hat OpenShift]
** Red Hat Application Foundation
*** https://access.redhat.com/products/quarkus[Quarkus]
* Other open source products:
** https://helm.sh/[Helm]


[#in_depth]
== An in-depth look at the solution's architecture

As Globex gears to support access to their core services from other channels/applications, they adopt a Kubernetes native approach to application connectivity through Red Hat Connectivity Link. 

In this solution we will look at a step-by-step approach to onboarding a new application and allowing for accessing the Globex services in a secure fashion

This pattern aims to cover the following use cases of Connectivity Link

* *Connect*: Setup app connectivity across service endpoints
* *Secure*: Secure traffic with automatic ACME-based TLS integration
* *Protect*: AuthPolicy and RateLimitPolicy help to protect services with our flexible and powerful policies 

[#more_tech]
== About the Technology Stack

=== What is GatewayAPI
https://gateway-api.sigs.k8s.io/[Gateway API^]This is the new standard for Ingress from the Kubernetes community. 

Gateway API is a relatively new k8s based API focused on traffic routing and is often referred to as the next generation of Ingress on kube. 

Used to define the Gateways and Routing rules for requests entering those gateways. Our supported provider is Istio via OpenShift Service Mesh

Connectiity Link (Kuadrant) provides connectivity, security and service protection capabilities in the form of Kubernetes CRDs that implement the Gateway API concept of policy attachment. These policy APIs can target specific Gateway API resources such as Gateways and HTTPRoutes to extend their capabilities and configuration. 

==== Istio as Gateway provider
Connectivity Link/Kuadrant's focus is on HTTP traffic and Istio | OSSM as a supported Gateway API implementation. Istio is the Gateway API provider that Connectivity Link integrates with (via WASM and Istio APIS) to provide service protection capabilities. It configures Envoy via the Istio control plane in order to enforce the applied policies and register components such as Authorino and Limitador.

==== HTTPRoute
HTTPRoute enables advanced routing capabilities for Ingress. It is a Gateway API type for specifying routing behavior of HTTP requests from a Gateway listener to an API object, i.e. Service. +
Ref: https://gateway-api.sigs.k8s.io/api-types/httproute/


=== What is Kuadrant
It enables platform engineers and application developers to easily connect, secure, and protect their services and infrastructure across multiple clusters with policies for TLS, DNS, application authentication & authorization, and rate limiting. Additionally, Kuadrant offers observability templates to further support infrastructure management. +
Ref: https://docs.kuadrant.io

=== Kuadrant: list of underlying components

==== DNS Operator

DNS operator consumes DNSRecord resources that are configured via the *DNSPolicy* api and applies them into the targeted cloud DNS provider AWS, Azure and Google DNS are our main targets

==== Cert Manager for TLS Policy

Manages TLS certificates for our components and for the Gateways. Consumes Certificate resources created by Kuadrant operator in response to the TLSPolicy.

====  Authorino Operator for Auth Policy

External authorization server fully manageable via Kubernetes Custom Resources. Supports JWT authentication, API key, mTLS, pattern-matching authz, OPA, K8s SA tokens, K8s RBAC, external metadata fetching, and more, with minimum to no coding at all, no rebuilding of your applications. +
Ref: https://docs.kuadrant.io/0.8.0/authorino/


==== Limitador Operator for Ratelimits

Limitador is a generic rate-limiter and can be enabled using RateLimit APIs

===  Policy Attachement 

Policy Attachment augments the behavior of an object to add additional settings that can't be described within the spec of that object. A "Policy Attachment" is a specific type of resprce that can affect specific settings across either one object (this is "Direct Policy Attachment"), or objects in a hierarchy (this is "Inherited Policy Attachment"). +
Ref: https://gateway-api.sigs.k8s.io/reference/policy-attachment/


==== Defaults and overrides
For example, we can apply a RateLimit Policy to a Gateway which will by *default* be applied across all the resources (such as HTTPRoute) attached to it. But developers might want to apply different rate limits based on the service endpoint they are exposing. This could be higher than the Gateway's rate limits for inexpensive requests, or could be quite low if for e.g., they would like to expose an LLM API as a service. This can be acheved by applying another RateLimit Policy to the HTTPRoute thereby *overriding* the default value.

The same can be extended for AuthPolicy - with a *default* deny-all policy which setup the system for zero-trust. Each developers can *override* this with AuthPolucy based on for e.g. APIKey or JWT Token through new AuthPolicy CRS applied for each of their service endpoints.

Ref: https://docs.kuadrant.io/0.8.0/architecture/rfcs/0009-defaults-and-overrides/#policy-spec-resembling-more-the-target-spec